#!/bin/bash

export KERNELNAME=Deagle

export LOCALVERSION=Beta

export KBUILD_BUILD_USER=builder

export KBUILD_BUILD_HOST=deagle

export TOOLCHAIN=clang

export DEVICES=whyred,tulip,wayne,lavender

source helper

gen_toolchain

send_msg "Start building..."

START=$(date +"%s")

for i in ${DEVICES//,/ }
do
	build ${i} nonoverclock
done

send_msg "Build OC..."

git apply oc.patch

for i in ${DEVICES//,/ }
do
	if [ $i == "whyred" ] || [ $i == "tulip" ]
	then
		build ${i} overclock
	fi
done

END=$(date +"%s")

DIFF=$(( END - START ))

send_msg "Build complete in $((DIFF / 60))m $((DIFF % 60))s"
